from __future__ import annotations

from dataclasses import asdict, dataclass
from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    PROJECT_READ_ONLY = "PROJECT_READ_ONLY"
    PROJECT_METADATA_INCONSISTENT = "PROJECT_METADATA_INCONSISTENT"
    PROJECT_SCHEMA_UNSUPPORTED = "PROJECT_SCHEMA_UNSUPPORTED"
    ASSET_PATH_OUTSIDE_PROJECT = "ASSET_PATH_OUTSIDE_PROJECT"
    INVALID_ARCHIVE = "INVALID_ARCHIVE"
    MIGRATION_FAILED = "MIGRATION_FAILED"
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_REFERENCED = "ASSET_REFERENCED"
    INVALID_ASSET_CONTENT = "INVALID_ASSET_CONTENT"
    ASSET_CONTENT_MISMATCH = "ASSET_CONTENT_MISMATCH"
    INVALID_SELECTION = "INVALID_SELECTION"
    TOOL_ARGUMENT_INVALID = "TOOL_ARGUMENT_INVALID"
    TOOL_NOT_ALLOWED = "TOOL_NOT_ALLOWED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    SECURITY_AUTH_REQUIRED = "SECURITY_AUTH_REQUIRED"
    SECURITY_ORIGIN_REJECTED = "SECURITY_ORIGIN_REJECTED"
    SECURITY_CAPABILITY_INVALID = "SECURITY_CAPABILITY_INVALID"
    SECURE_STORAGE_UNAVAILABLE = "SECURE_STORAGE_UNAVAILABLE"
    LOCAL_STORAGE_UNAVAILABLE = "LOCAL_STORAGE_UNAVAILABLE"
    DATABASE_BUSY = "DATABASE_BUSY"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    PROVIDER_NOT_CONFIGURED = "PROVIDER_NOT_CONFIGURED"
    PROVIDER_AUTH_FAILED = "PROVIDER_AUTH_FAILED"
    PROVIDER_RATE_LIMITED = "PROVIDER_RATE_LIMITED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    JOB_TIMEOUT = "JOB_TIMEOUT"
    JOB_CANCELLED = "JOB_CANCELLED"
    JOB_UNKNOWN_SUBMISSION = "JOB_UNKNOWN_SUBMISSION"
    IMAGE_DECODE_FAILED = "IMAGE_DECODE_FAILED"
    MODEL3D_PARSE_FAILED = "MODEL3D_PARSE_FAILED"
    SECURITY_UNTRUSTED_URL = "SECURITY_UNTRUSTED_URL"


@dataclass
class DomainErrorV1(Exception):
    code: str
    user_message: str
    recoverable: bool = False
    retry_after_seconds: int | None = None
    technical_message: str | None = None
    details_ref: str | None = None
    details: dict[str, Any] | None = None

    def as_dict(self) -> dict[str, Any]:
        return {key: value for key, value in asdict(self).items() if value is not None}
